// Code generaTed by fileb0x at "2019-08-03 22:30:16.992016831 +0800 CST m=+0.443274294" from config file "b0x.yml" DO NOT EDIT.
// modified(2018-11-16 23:20:23 +0800 CST)
// original path: dist/images/collapse.gif

package swaggerFiles

import (
	"os"
)

// FileImagesCollapseGif is "/images/collapse.gif"
var FileImagesCollapseGif = []byte("\x47\x49\x46\x38\x39\x61\x0b\x00\x0b\x00\x91\x00\x00\x4a\x4d\x4a\x7b\x7d\x7b\xff\xff\xff\x00\x00\x00\x21\xf9\x04\x00\x00\x00\x00\x00\x2c\x00\x00\x00\x00\x0b\x00\x0b\x00\x00\x02\x16\x8c\x8f\x26\xcb\xac\xdd\x1e\x5c\x72\x3e\x80\x31\x0d\xd3\xf1\x2e\x54\x90\x18\x25\x66\x01\x00\x3b")

func init() {

	f, err := FS.OpenFile(CTX, "/images/collapse.gif", os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0777)
	if err != nil {
		panic(err)
	}

	_, err = f.Write(FileImagesCollapseGif)
	if err != nil {
		panic(err)
	}

	err = f.Close()
	if err != nil {
		panic(err)
	}
}
