info:
  contact: {}
  license: {}
paths:
  /:
    get:
      description: hello接口
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: hello接口
      tags:
      - hello
